version: "3.9"

services:
  order_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
      POSTGRES_DB: payment_db
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  order_service:
    build: ./orders_service
    depends_on:
      order_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://order_user:order_pass@order_db:5432/order_db
      BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      GRPC_PORT: 50051
    # Чтобы открыть наружный порт, раскомментируйте:
    ports:
      - "50051:50051"
    #   - "8001:80"

  payment_service:
    build: ./payments_service
    depends_on:
      payment_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://payment_user:payment_pass@payment_db:5432/payment_db
      BROKER_URL: amqp://guest:guest@rabbitmq:5672/
    # Чтобы открыть наружный порт, раскомментируйте:
    # ports:
    #   - "8002:80"

  api_gateway:
    build: ./api_gateway
    depends_on:
      - order_service
      - payment_service
    environment:
      ORDER_SERVICE_URL: http://order_service:80
      PAYMENT_SERVICE_URL: http://payment_service:80
      ORDER_SERVICE_GRPC: order_service:50051
    ports:
      - "8000:80"
    # при необходимости можно добавить healthcheck для проверки gateway

volumes:
  order_db_data:
  payment_db_data:
