# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\x06orders\x1a\x1bgoogle/protobuf/empty.proto\"_\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"J\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"3\n\x12ListOrdersResponse\x12\x1d\n\x06orders\x18\x01 \x03(\x0b\x32\r.orders.Order2\xbe\x01\n\x0cOrderService\x12\x38\n\x0b\x43reateOrder\x12\x1a.orders.CreateOrderRequest\x1a\r.orders.Order\x12\x32\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\r.orders.Order\x12@\n\nListOrders\x12\x16.google.protobuf.Empty\x1a\x1a.orders.ListOrdersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=60
  _globals['_ORDER']._serialized_end=155
  _globals['_CREATEORDERREQUEST']._serialized_start=157
  _globals['_CREATEORDERREQUEST']._serialized_end=231
  _globals['_GETORDERREQUEST']._serialized_start=233
  _globals['_GETORDERREQUEST']._serialized_end=268
  _globals['_LISTORDERSRESPONSE']._serialized_start=270
  _globals['_LISTORDERSRESPONSE']._serialized_end=321
  _globals['_ORDERSERVICE']._serialized_start=324
  _globals['_ORDERSERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
